
hyperborean = Pantheon.create(name: "Hyperboreans")

pre_socratic = School.create(name: "Pre-Socratic", description: "Pre-Socratic philosophy, also known as early Greek philosophy, is ancient Greek philosophy before Socrates. Pre-Socratic philosophers were mostly interested in cosmology, the beginning and the substance of the universe, but the inquiries of these early philosophers spanned the workings of the natural world as well as human society, ethics, and religion. They sought explanations based on natural law rather than the actions of gods. Their work and writing has been almost entirely lost. Knowledge of their views comes from testimonia, i.e. later authors' discussions of the work of pre-Socratics. Philosophy found fertile ground in the ancient Greek world because of the close ties with neighboring civilizations and the rise of autonomous civil entities, poleis.

    Pre-Socratic philosophy began in the 6th century BCE with the three Milesians: Thales, Anaximander, and Anaximenes. They all attributed the arche (a word that could take the meaning of 'origin,' 'substance' or 'principle') of the world to, respectively, water, apeiron (the unlimited), and air governed by nous (mind or intelligence). Another three pre-Socratic philosophers came from nearby Ionian towns: Xenophanes, Heraclitus, and Pythagoras. Xenophanes is known for his critique of the anthropomorphism of gods. Heraclitus, who was notoriously difficult to understand, is known for his maxim on impermanence, ta panta rhei, and for attributing fire to be the arche of the world. Pythagoras created a cult-like following that advocated that the universe was made up of numbers. The Eleatic school (Parmenides, Zeno of Elea, and Melissus) followed in the 5th century BCE. Parmenides claimed that only one thing exists and nothing can change. Zeno and Melissus mainly defended Parmenides' opinion. Anaxagoras and Empedocles offered a pluralistic account of how the universe was created. Leucippus and Democritus are known for their atomism, and their views that only void and matter exist. The Sophists advanced critical thinking and philosophical relativism.
    
    The impact of the pre-Socratics has been enormous. The pre-Socratics invented some of the central concepts of Western civilization, such as naturalism and rationalism, and paved the way for scientific methodology.")

pythagoras = Philosopher.create(name: "Pythagoras", school: pre_socratic, lifespan: "c. 570 – c. 495 BC", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Pythagoras_in_the_Roman_Forum%2C_Colosseum.jpg/800px-Pythagoras_in_the_Roman_Forum%2C_Colosseum.jpg", bio: "Pythagoras of Samos (c. 570 – c. 495 BC) was an ancient Ionian Greek philosopher and the eponymous founder of Pythagoreanism. His political and religious teachings were well known in Magna Graecia and influenced the philosophies of Plato, Aristotle, and, through them, Western philosophy. Knowledge of his life is clouded by legend, but he appears to have been the son of Mnesarchus, a gem-engraver on the island of Samos. Modern scholars disagree regarding Pythagoras's education and influences, but they do agree that, around 530 BC, he travelled to Croton in southern Italy, where he founded a school in which initiates were sworn to secrecy and lived a communal, ascetic lifestyle. This lifestyle entailed a number of dietary prohibitions, traditionally said to have included vegetarianism, although modern scholars doubt that he ever advocated for complete vegetarianism.

The teaching most securely identified with Pythagoras is metempsychosis, or the 'transmigration of souls', which holds that every soul is immortal and, upon death, enters into a new body. He may have also devised the doctrine of musica universalis, which holds that the planets move according to mathematical equations and thus resonate to produce an inaudible symphony of music. Scholars debate whether Pythagoras developed the numerological and musical teachings attributed to him, or if those teachings were developed by his later followers, particularly Philolaus of Croton. Following Croton's decisive victory over Sybaris in around 510 BC, Pythagoras's followers came into conflict with supporters of democracy and Pythagorean meeting houses were burned. Pythagoras may have been killed during this persecution, or escaped to Metapontum, where he eventually died.

In antiquity, Pythagoras was credited with many mathematical and scientific discoveries, including the Pythagorean theorem, Pythagorean tuning, the five regular solids, the Theory of Proportions, the sphericity of the Earth, and the identity of the morning and evening stars as the planet Venus. It was said that he was the first man to call himself a philosopher ('lover of wisdom') and that he was the first to divide the globe into five climatic zones. Classical historians debate whether Pythagoras made these discoveries, and many of the accomplishments credited to him likely originated earlier or were made by his colleagues or successors. Some accounts mention that the philosophy associated with Pythagoras was related to mathematics and that numbers were important, but it is debated to what extent, if at all, he actually contributed to mathematics or natural philosophy.

Pythagoras influenced Plato, whose dialogues, especially his Timaeus, exhibit Pythagorean teachings. Pythagorean ideas on mathematical perfection also impacted ancient Greek art. His teachings underwent a major revival in the first century BC among Middle Platonists, coinciding with the rise of Neopythagoreanism. Pythagoras continued to be regarded as a great philosopher throughout the Middle Ages and his philosophy had a major impact on scientists such as Nicolaus Copernicus, Johannes Kepler, and Isaac Newton. Pythagorean symbolism was used throughout early modern European esotericism, and his teachings as portrayed in Ovid's Metamorphoses influenced the modern vegetarian movement.")

Quote.create(passage: "As soon as laws are necessary for men, they are no longer fit for freedom.", philosopher: pythagoras)
Quote.create(passage: "Above all things, reverence yourself.", philosopher: pythagoras)
Quote.create(passage: "In anger we should refrain both from speech and action.", philosopher: pythagoras)
Quote.create(passage: "There is geometry in the humming of the strings, there is music in the spacing of the spheres.", philosopher: pythagoras)
Quote.create(passage: "Concern should drive us into action and not into a depression. No man is free who cannot control himself.", philosopher: pythagoras)
Quote.create(passage: "Choose rather to be strong of soul than strong of body.", philosopher: pythagoras)

parmenides = Philosopher.create(name: "Parminedes", school: pre_socratic, lifespan: "Born c. 515 BC", image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Parmenides.jpg", bio: "Parmenides of Elea was a pre-Socratic Greek philosopher from Elea in Magna Graecia (meaning 'Great Greece,'' the term which Romans gave to Greek-populated coastal areas in Southern Italy). He is thought to have been in his prime (or 'floruit') around 475 BC.

Parmenides has been considered the founder of ontology or metaphysics and has influenced the whole history of Western philosophy. He was the founder of the Eleatic school of philosophy, which also included Zeno of Elea and Melissus of Samos. Zeno's paradoxes of motion were to defend Parmenides' view.

The single known work by Parmenides is a poem whose original title is unknown but which is often referred to as On Nature. Only fragments of it survive, but its importance lies in the fact that it contains the first sustained argument in the history of Western philosophy. In his poem, Parmenides prescribes two views of reality. In 'the way of truth' (a part of the poem), he explains how all reality is one, change is impossible, and existence is timeless, uniform, and necessary. In 'the way of opinion', Parmenides explains the world of appearances, in which one's sensory faculties lead to conceptions which are false and deceitful, yet he does offer a cosmology.

Parmenides' philosophy has been explained with the slogan 'whatever is is, and what is not cannot be'. He is also credited with the phrase out of nothing nothing comes. He argues that 'A is not' can never be thought or said truthfully, and thus despite appearances everything exists as one, giant, unchanging thing. This is generally considered one of the first digressions into the philosophical concept of being, and has been contrasted with Heraclitus's statement that 'No man ever steps into the same river twice' as one of the first digressions into the philosophical concept of becoming. Scholars have generally believed that either Parmenides was responding to Heraclitus, or Heraclitus to Parmenides.

Parmenides' views have remained relevant in philosophy, even thousands of years after his death. Alexius Meinong, much like Parmenides, defended the view that even the 'golden mountain' is real since it can be talked about. The rivalry between Heraclitus and Parmenides has also been re-introduced in debates in the philosophy of time between A theory and B theory.")

Quote.create(passage: "We can speak and think only of what exists. And what exists is uncreated and imperishable for it is whole and unchanging and complete. It was not or nor shall be different since it is now, all at once, one and continuous.", philosopher: parmenides)
Quote.create(passage: "It is all one to me where I begin; for I shall come back again there", philosopher: parmenides)
Quote.create(passage: "To be and to have meaning are the same.", philosopher: parmenides)
Quote.create(passage: "Wherefore all these things are but the names which mortals have given, believing them to be true", philosopher: parmenides)
Quote.create(passage: "Let reason alone decide.", philosopher: parmenides)
Quote.create(passage: "Tis necessary for thee to learn all things, both the abiding essence of persuasive truth, and men's opinions in which rests no true belief", philosopher: parmenides)

empedocles = Philosopher.create(name: "Empedocles", school: pre_socratic, lifespan: "c. 494 – c. 434 BC", image_url: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Empedocles_in_Thomas_Stanley_History_of_Philosophy.jpg", bio: "Empedocles was a Greek pre-Socratic philosopher and a native citizen of Akragas,a Greek city in Sicily. Empedocles' philosophy is best known for originating the cosmogonic theory of the four classical elements. He also proposed forces he called Love and Strife which would mix and separate the elements, respectively.

Influenced by Pythagoras (died c. 495 BC) and the Pythagoreans, Empedocles challenged the practice of animal sacrifice and killing animals for food. He developed a distinctive doctrine of reincarnation. He is generally considered the last Greek philosopher to have recorded his ideas in verse. Some of his work survives, more than is the case for any other pre-Socratic philosopher. Empedocles' death was mythologized by ancient writers, and has been the subject of a number of literary treatments.")

Quote.create(passage: "God is a circle whose center is everywhere, and its circumference nowhere.", philosopher: empedocles)
Quote.create(passage: "No mortal thing has a beginning, nor does it end in death and obliteration; there is only a mixing and then separating of what was mixed, but by mortal men these processes are named 'beginnings.'", philosopher: empedocles)
Quote.create(passage: "The force that unites the elements to become all things is Love, also called Aphrodite; Love brings together dissimilar elements into a unity, to become a composite thing. Love is the same force that human beings find at work in themselves whenever they feel joy, love and peace. Strife, on the other hand, is the force responsible for the dissolution of the one back into its many, the four elements of which it was composed.", philosopher: empedocles)
Quote.create(passage: "It was not the mixture, O men, of blood and breath that made the beginning and substance of your souls, though your earthborn and mortal body is framed of those things. But your soul has come hither from another place.", philosopher: empedocles)
Quote.create(passage: "Weak and narrow are the powers implanted in the limbs of men; many the woes that fall on them and blunt the edge of thought; short is the measure of the life in death through which they toil; then are they borne away, like smoke they vanish into air, and what they dream they know is but the little each hath stumbled on in wandering about the world; yet boast they all that they have learned the whole—vain fools! for what that is, no eye hath seen, no ear hath heard, nor can it be conceived by mind of man. Thou, then, since thou hast fallen to this place, shalt know no more than human wisdom may attain.", philosopher: empedocles)
Quote.create(passage: "Many fires burn below the surface.", philosopher: empedocles)



socratic = School.create(name: "Socratic", description: "The Classical period of ancient Greek philosophy centers on Socrates and the two generations of students following him.

    Socrates experienced a life-changing event when his friend, Chaerephon visited the Oracle of Delphi where the Pythia told him that no one in Athens was wiser than Socrates. Learning of this, Socrates subsequently spent much of his life questioning anyone in Athens who would engage him, in order to investigate the Pithia's claim.[12] Socrates developed a critical approach, now called the Socratic method, to examine people's views. He focused on issues of human life: eudaimonia, justice, beauty, truth, and virtue. Although Socrates wrote nothing himself, two of his disciples, Plato and Xenophon, wrote about some of his conversations, although Plato also deployed Socrates as a fictional character in some of his dialogues. These Socratic dialogues display the Socratic method being applied to examine philosophical problems.
    
    Socrates's questioning earned him enemies who eventually accused him of impiety and corrupting the youth. The Athenian democracy tried him, was found guilty, and was sentenced to death. Although his friends offered to help him escape from prison, Socrates chose to remain in Athens and abide by his principles. His execution consisted of drinking poison hemlock. He died in 399 BCE.
    
    After Socrates' death, Plato founded the Platonic Academy and Platonic philosophy. As Socrates had done, Plato identified virtue with knowledge. This led him to questions of epistemology on what knowledge is and how it is acquired.
    
    Socrates had several other students who also founded schools of philosophy. Two of these were short-lived: the Eretrian school, founded by Phaedo of Elis, and the Megarian school, founded by Euclid of Megara. Two others were long-lasting: Cynicism, founded by Antisthenes, and Cyrenaicism, founded by Aristippus. The Cynics considered life's purpose to live in virtue, in agreement with nature, rejecting all conventional desires for wealth, power, and fame, leading a simple life free from all possessions. The Cyrenaics promoted a philosophy nearly opposite that of the Cynics, endorsing hedonism, holding that pleasure was the supreme good, especially immediate gratifications; and that people could only know their own experiences, beyond that truth was unknowable.
    
    
    Aristotle in The School of Athens, by Raphael
    The final school of philosophy to be established during the Classical period was the Peripatetic school, founded by Plato's student, Aristotle. Aristotle wrote widely about topics of philosophical concern, including physics, biology, zoology, metaphysics, aesthetics, poetry, theater, music, rhetoric, politics, and logic. Aristotelian logic was the first type of logic to attempt to categorize every valid syllogism. His epistemology comprised an early form empiricism. Aristotle criticized Plato's metaphysics as being poetic metaphor, with its greatest failing being the lack of an explanation for change. Aristotle proposed the four causes model to explain change - material, efficient, formal, and final - all of which were grounded on what Aristotle termed the unmoved mover. His ethical views identified eudaimonia as the ultimate good, as it was good in itself. He thought that eudaimonia could be achieved by living according to human nature, which is to live with reason and virtue, defining virtue as the golden mean between extremes. Aristotle saw politics as the highest art, as all other pursuits are subservient to its goal of improving society. The state should aim to maximize the opportunities for the pursuit of reason and virtue through leisure, learning, and contemplation. Aristotle tutored Alexander the Great, who conquered much of the ancient Western world. Hellenization and Aristotelian philosophy have exercised considerable influence on almost all subsequent Western and Middle Eastern philosophers.")

socrates = Philosopher.create(name: "Socrates", school: socratic, image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Socrate_du_Louvre.jpg/800px-Socrate_du_Louvre.jpg", bio: "Socrates was a Greek philosopher from Athens who is credited as a founder of Western philosophy and the first moral philosopher of the Western ethical tradition of thought. An enigmatic figure, Socrates authored no texts and is known mainly through the posthumous accounts of classical writers, particularly his students Plato and Xenophon. These accounts are written as dialogues, in which Socrates and his interlocutors examine a subject in the style of question and answer, usually with Socrates taking the lead, and gave rise to the Socratic dialogue literary genre. Contradictory accounts of Socrates make a reconstruction of the history of his life nearly impossible, a situation known as the Socratic problem. Socrates was a polarizing figure in Athenian society. In 399 BC, he was accused of corrupting the youth and failing to acknowledge the city's official gods. After a trial that lasted a day, he was sentenced to death. He spent his last day in prison, refusing to escape.

Plato's dialogues are among the most comprehensive accounts of Socrates to survive from antiquity, from which Socrates has become renowned for his contributions to the fields of rationalism, ethics and epistemology. This Platonic Socrates lends his name to the concept of the Socratic method, and also to Socratic irony. The Socratic method of questioning or elenchus takes shape in dialogue using short questions and answers, epitomized by those Platonic texts in which Socrates and his interlocutors examine various aspects of an issue or an abstract meaning, usually relating to one of the virtues, and find themselves completely unable to define what they thought they understood. Socrates is known for proclaiming his total ignorance; he used to say that the only thing he was aware of was his ignorance, seeking to imply that the realization of our ignorance is the first step in philosophizing.

Socrates exerted a strong influence on philosophers in later antiquity and has continued to do so in the modern era. Almost all major philosophical currents in the classical era saw themselves as continuing the work of Socrates. Socrates was studied by medieval and Islamic scholars and played an important role in the thought of the Italian Renaissance, particularly within the humanist movement. Interest in Socrates continued unabated, as reflected in the works of Søren Kierkegaard and Friedrich Nietzsche. Depictions of Socrates in art, literature and popular culture have made him one of the most widely known figures in the Western philosophical tradition.", lifespan: "470–399 BC")


Quote.create(passage: "An unexamined life is not worth living.", philosopher: socrates)
Quote.create(passage: "One thing only I know, and that is that I know nothing.", philosopher: socrates)
Quote.create(passage: "To find yourself, think for yourself.", philosopher: socrates)
Quote.create(passage: "When the debate is over, slander becomes the tool of the loser.", philosopher: socrates)

plato = Philosopher.create(name: "Plato", school: socratic, image_url: "https://www.laphamsquarterly.org/sites/default/files/styles/tall_rectangle_custom_user_large_2x/public/images/contributor/plato_360x450.jpg?itok=HUiuGqkr&timestamp=1414179137", bio: "Plato was an Athenian philosopher during the Classical period in Ancient Greece, founder of the Platonist school of thought and the Academy, the first institution of higher learning in the Western world.

He is widely considered one of the most important and influential individuals in human history, and the pivotal figure in the history of Ancient Greek and Western philosophy, along with his teacher, Socrates, and his most famous student, Aristotle. Plato has also often been cited as one of the founders of Western religion and spirituality. The so-called neoplatonism of philosophers such as Plotinus and Porphyry greatly influenced Christianity through Church Fathers such as Augustine. Alfred North Whitehead once noted: 'the safest general characterization of the European philosophical tradition is that it consists of a series of footnotes to Plato.'

Plato was an innovator of the written dialogue and dialectic forms in philosophy. Plato is also considered the founder of Western political philosophy. His most famous contribution is the theory of Forms known by pure reason, in which Plato presents a solution to the problem of universals known as Platonism (also ambiguously called either Platonic realism or Platonic idealism). He is also the namesake of Platonic love and the Platonic solids.

His own most decisive philosophical influences are usually thought to have been along with Socrates, the pre-Socratics Pythagoras, Heraclitus and Parmenides, although few of his predecessors' works remain extant and much of what we know about these figures today derives from Plato himself. Unlike the work of nearly all of his contemporaries, Plato's entire body of work is believed to have survived intact for over 2,400 years. Although their popularity has fluctuated, Plato's works have consistently been read and studied.", lifespan: " 428/427 or 424/423 – 348/347 BC")

Quote.create(passage: "Thinking: the talking of the soul with itself.", philosopher: plato)
Quote.create(passage: "The greatest wealth is to live content with little.", philosopher: plato)
Quote.create(passage: "Be kind, for everyone you meet is fighting a hard battle.", philosopher: plato)
Quote.create(passage: "Music is a moral law. It gives soul to the universe, wings to the mind, flight to the imagination, and charm and gaiety to life and to everything.", philosopher: plato)
Quote.create(passage: "The first and greatest victory is to conquer yourself; to be conquered by yourself is of all things most shameful and vile.", philosopher: plato)

Work.create(name: "The Republic", link: "https://www.gutenberg.org/files/1497/1497-h/1497-h.htm", philosopher: plato)
Work.create(name: "Apology", link: "http://classics.mit.edu/Plato/apology.html", philosopher: plato)



aristotle = Philosopher.create(name: "Aristotle", school: socratic, image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Aristotle_Altemps_Inv8575.jpg/800px-Aristotle_Altemps_Inv8575.jpg", bio: "Aristotle was a Greek philosopher and polymath during the Classical period in Ancient Greece. Taught by Plato, he was the founder of the Lyceum, the Peripatetic school of philosophy, and the Aristotelian tradition. His writings cover many subjects including physics, biology, zoology, metaphysics, logic, ethics, aesthetics, poetry, theatre, music, rhetoric, psychology, linguistics, economics, politics, meteorology, geology and government. Aristotle provided a complex synthesis of the various philosophies existing prior to him. It was above all from his teachings that the West inherited its intellectual lexicon, as well as problems and methods of inquiry. As a result, his philosophy has exerted a unique influence on almost every form of knowledge in the West and it continues to be a subject of contemporary philosophical discussion.

Little is known about his life. Aristotle was born in the city of Stagira in Northern Greece. His father, Nicomachus, died when Aristotle was a child, and he was brought up by a guardian. At seventeen or eighteen years of age he joined Plato's Academy in Athens and remained there until the age of thirty-seven (c. 347 BC). Shortly after Plato died, Aristotle left Athens and, at the request of Philip II of Macedon, tutored Alexander the Great beginning in 343 BC. He established a library in the Lyceum which helped him to produce many of his hundreds of books on papyrus scrolls. Though Aristotle wrote many elegant treatises and dialogues for publication, only around a third of his original output has survived, none of it intended for publication.

Aristotle's views profoundly shaped medieval scholarship. The influence of physical science extended from Late Antiquity and the Early Middle Ages into the Renaissance, and were not replaced systematically until the Enlightenment and theories such as classical mechanics were developed. Some of Aristotle's zoological observations found in his biology, such as on the hectocotyl (reproductive) arm of the octopus, were disbelieved until the 19th century. He also influenced Judeo-Islamic philosophies (800–1400) during the Middle Ages, as well as Christian theology, especially the Neoplatonism of the Early Church and the scholastic tradition of the Catholic Church. Aristotle was revered among medieval Muslim scholars as 'The First Teacher', and among medieval Christians like Thomas Aquinas as simply 'The Philosopher', while the poet Dante called him 'the master of those who know'. His works contain the earliest known formal study of logic, and were studied by medieval scholars such as Peter Abelard and John Buridan.

Aristotle's influence on logic continued well into the 19th century. In addition, his ethics, though always influential, gained renewed interest with the modern advent of virtue ethics.

Aristotle has been called 'the father of logic', 'the father of biology', 'the father of political science', 'the father of zoology', 'the father of embryology', 'the father of natural law', 'the father of scientific method', 'the father of rhetoric', 'the father of psychology', 'the father of realism', 'the father of criticism', 'the father of individualism', 'the father of teleology', and 'the father of meteorology'.", lifespan: "384–322 BC")


Quote.create(passage: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", philosopher: aristotle)
Quote.create(passage: "A friend to all is a friend to none.", philosopher: aristotle)
Quote.create(passage: "Pleasure in the job puts perfection in the work.", philosopher: aristotle)
Quote.create(passage: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", philosopher: aristotle)
Quote.create(passage: "The whole is more than the sum of its parts.", philosopher: aristotle)
Quote.create(passage: "The law is reason, free from passion.", philosopher: aristotle)

