# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

hyperborean = Pantheon.create(name: "Hyperboreans")
socratic = School.create(name: "Socratics", description: "The Classical period of ancient Greek philosophy centers on Socrates and the two generations of students following him.

    Socrates experienced a life-changing event when his friend, Chaerephon visited the Oracle of Delphi where the Pythia told him that no one in Athens was wiser than Socrates. Learning of this, Socrates subsequently spent much of his life questioning anyone in Athens who would engage him, in order to investigate the Pithia's claim.[12] Socrates developed a critical approach, now called the Socratic method, to examine people's views. He focused on issues of human life: eudaimonia, justice, beauty, truth, and virtue. Although Socrates wrote nothing himself, two of his disciples, Plato and Xenophon, wrote about some of his conversations, although Plato also deployed Socrates as a fictional character in some of his dialogues. These Socratic dialogues display the Socratic method being applied to examine philosophical problems.
    
    Socrates's questioning earned him enemies who eventually accused him of impiety and corrupting the youth. The Athenian democracy tried him, was found guilty, and was sentenced to death. Although his friends offered to help him escape from prison, Socrates chose to remain in Athens and abide by his principles. His execution consisted of drinking poison hemlock. He died in 399 BCE.
    
    After Socrates' death, Plato founded the Platonic Academy and Platonic philosophy. As Socrates had done, Plato identified virtue with knowledge. This led him to questions of epistemology on what knowledge is and how it is acquired.
    
    Socrates had several other students who also founded schools of philosophy. Two of these were short-lived: the Eretrian school, founded by Phaedo of Elis, and the Megarian school, founded by Euclid of Megara. Two others were long-lasting: Cynicism, founded by Antisthenes, and Cyrenaicism, founded by Aristippus. The Cynics considered life's purpose to live in virtue, in agreement with nature, rejecting all conventional desires for wealth, power, and fame, leading a simple life free from all possessions. The Cyrenaics promoted a philosophy nearly opposite that of the Cynics, endorsing hedonism, holding that pleasure was the supreme good, especially immediate gratifications; and that people could only know their own experiences, beyond that truth was unknowable.
    
    
    Aristotle in The School of Athens, by Raphael
    The final school of philosophy to be established during the Classical period was the Peripatetic school, founded by Plato's student, Aristotle. Aristotle wrote widely about topics of philosophical concern, including physics, biology, zoology, metaphysics, aesthetics, poetry, theater, music, rhetoric, politics, and logic. Aristotelian logic was the first type of logic to attempt to categorize every valid syllogism. His epistemology comprised an early form empiricism. Aristotle criticized Plato's metaphysics as being poetic metaphor, with its greatest failing being the lack of an explanation for change. Aristotle proposed the four causes model to explain change - material, efficient, formal, and final - all of which were grounded on what Aristotle termed the unmoved mover. His ethical views identified eudaimonia as the ultimate good, as it was good in itself. He thought that eudaimonia could be achieved by living according to human nature, which is to live with reason and virtue, defining virtue as the golden mean between extremes. Aristotle saw politics as the highest art, as all other pursuits are subservient to its goal of improving society. The state should aim to maximize the opportunities for the pursuit of reason and virtue through leisure, learning, and contemplation. Aristotle tutored Alexander the Great, who conquered much of the ancient Western world. Hellenization and Aristotelian philosophy have exercised considerable influence on almost all subsequent Western and Middle Eastern philosophers.")

socrates = Philosopher.create(name: "Socrates", school: socratic, bio: "Socrates was a Greek philosopher from Athens who is credited as a founder of Western philosophy and the first moral philosopher of the Western ethical tradition of thought. An enigmatic figure, Socrates authored no texts and is known mainly through the posthumous accounts of classical writers, particularly his students Plato and Xenophon. These accounts are written as dialogues, in which Socrates and his interlocutors examine a subject in the style of question and answer, usually with Socrates taking the lead, and gave rise to the Socratic dialogue literary genre. Contradictory accounts of Socrates make a reconstruction of the history of his life nearly impossible, a situation known as the Socratic problem. Socrates was a polarizing figure in Athenian society. In 399 BC, he was accused of corrupting the youth and failing to acknowledge the city's official gods. After a trial that lasted a day, he was sentenced to death. He spent his last day in prison, refusing to escape.

Plato's dialogues are among the most comprehensive accounts of Socrates to survive from antiquity, from which Socrates has become renowned for his contributions to the fields of rationalism, ethics and epistemology. This Platonic Socrates lends his name to the concept of the Socratic method, and also to Socratic irony. The Socratic method of questioning or elenchus takes shape in dialogue using short questions and answers, epitomized by those Platonic texts in which Socrates and his interlocutors examine various aspects of an issue or an abstract meaning, usually relating to one of the virtues, and find themselves completely unable to define what they thought they understood. Socrates is known for proclaiming his total ignorance; he used to say that the only thing he was aware of was his ignorance, seeking to imply that the realization of our ignorance is the first step in philosophizing.

Socrates exerted a strong influence on philosophers in later antiquity and has continued to do so in the modern era. Almost all major philosophical currents in the classical era saw themselves as continuing the work of Socrates. Socrates was studied by medieval and Islamic scholars and played an important role in the thought of the Italian Renaissance, particularly within the humanist movement. Interest in Socrates continued unabated, as reflected in the works of Søren Kierkegaard and Friedrich Nietzsche. Depictions of Socrates in art, literature and popular culture have made him one of the most widely known figures in the Western philosophical tradition.", lifespan: "470–399 BC")


Quote.create(passage: "An unexamined life is not worth living.", philosopher: socrates)
Quote.create(passage: "One thing only I know, and that is that I know nothing.", philosopher: socrates)
Quote.create(passage: "To find yourself, think for yourself.", philosopher: socrates)
Quote.create(passage: "When the debate is over, slander becomes the tool of the loser.", philosopher: socrates)