# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

hyperborean = Pantheon.create(name: "Hyperboreans")
socratic = School.create(name: "Socratics", description: "The Classical period of ancient Greek philosophy centers on Socrates and the two generations of students following him.

    Socrates experienced a life-changing event when his friend, Chaerephon visited the Oracle of Delphi where the Pythia told him that no one in Athens was wiser than Socrates. Learning of this, Socrates subsequently spent much of his life questioning anyone in Athens who would engage him, in order to investigate the Pithia's claim.[12] Socrates developed a critical approach, now called the Socratic method, to examine people's views. He focused on issues of human life: eudaimonia, justice, beauty, truth, and virtue. Although Socrates wrote nothing himself, two of his disciples, Plato and Xenophon, wrote about some of his conversations, although Plato also deployed Socrates as a fictional character in some of his dialogues. These Socratic dialogues display the Socratic method being applied to examine philosophical problems.
    
    Socrates's questioning earned him enemies who eventually accused him of impiety and corrupting the youth. The Athenian democracy tried him, was found guilty, and was sentenced to death. Although his friends offered to help him escape from prison, Socrates chose to remain in Athens and abide by his principles. His execution consisted of drinking poison hemlock. He died in 399 BCE.
    
    After Socrates' death, Plato founded the Platonic Academy and Platonic philosophy. As Socrates had done, Plato identified virtue with knowledge. This led him to questions of epistemology on what knowledge is and how it is acquired.
    
    Socrates had several other students who also founded schools of philosophy. Two of these were short-lived: the Eretrian school, founded by Phaedo of Elis, and the Megarian school, founded by Euclid of Megara. Two others were long-lasting: Cynicism, founded by Antisthenes, and Cyrenaicism, founded by Aristippus. The Cynics considered life's purpose to live in virtue, in agreement with nature, rejecting all conventional desires for wealth, power, and fame, leading a simple life free from all possessions. The Cyrenaics promoted a philosophy nearly opposite that of the Cynics, endorsing hedonism, holding that pleasure was the supreme good, especially immediate gratifications; and that people could only know their own experiences, beyond that truth was unknowable.
    
    
    Aristotle in The School of Athens, by Raphael
    The final school of philosophy to be established during the Classical period was the Peripatetic school, founded by Plato's student, Aristotle. Aristotle wrote widely about topics of philosophical concern, including physics, biology, zoology, metaphysics, aesthetics, poetry, theater, music, rhetoric, politics, and logic. Aristotelian logic was the first type of logic to attempt to categorize every valid syllogism. His epistemology comprised an early form empiricism. Aristotle criticized Plato's metaphysics as being poetic metaphor, with its greatest failing being the lack of an explanation for change. Aristotle proposed the four causes model to explain change - material, efficient, formal, and final - all of which were grounded on what Aristotle termed the unmoved mover. His ethical views identified eudaimonia as the ultimate good, as it was good in itself. He thought that eudaimonia could be achieved by living according to human nature, which is to live with reason and virtue, defining virtue as the golden mean between extremes. Aristotle saw politics as the highest art, as all other pursuits are subservient to its goal of improving society. The state should aim to maximize the opportunities for the pursuit of reason and virtue through leisure, learning, and contemplation. Aristotle tutored Alexander the Great, who conquered much of the ancient Western world. Hellenization and Aristotelian philosophy have exercised considerable influence on almost all subsequent Western and Middle Eastern philosophers.")

socrates = Philosopher.create(name: "Socrates", school: socratic, bio: "Socrates was a Greek philosopher from Athens who is credited as a founder of Western philosophy and the first moral philosopher of the Western ethical tradition of thought. An enigmatic figure, Socrates authored no texts and is known mainly through the posthumous accounts of classical writers, particularly his students Plato and Xenophon. These accounts are written as dialogues, in which Socrates and his interlocutors examine a subject in the style of question and answer, usually with Socrates taking the lead, and gave rise to the Socratic dialogue literary genre. Contradictory accounts of Socrates make a reconstruction of the history of his life nearly impossible, a situation known as the Socratic problem. Socrates was a polarizing figure in Athenian society. In 399 BC, he was accused of corrupting the youth and failing to acknowledge the city's official gods. After a trial that lasted a day, he was sentenced to death. He spent his last day in prison, refusing to escape.

Plato's dialogues are among the most comprehensive accounts of Socrates to survive from antiquity, from which Socrates has become renowned for his contributions to the fields of rationalism, ethics and epistemology. This Platonic Socrates lends his name to the concept of the Socratic method, and also to Socratic irony. The Socratic method of questioning or elenchus takes shape in dialogue using short questions and answers, epitomized by those Platonic texts in which Socrates and his interlocutors examine various aspects of an issue or an abstract meaning, usually relating to one of the virtues, and find themselves completely unable to define what they thought they understood. Socrates is known for proclaiming his total ignorance; he used to say that the only thing he was aware of was his ignorance, seeking to imply that the realization of our ignorance is the first step in philosophizing.

Socrates exerted a strong influence on philosophers in later antiquity and has continued to do so in the modern era. Almost all major philosophical currents in the classical era saw themselves as continuing the work of Socrates. Socrates was studied by medieval and Islamic scholars and played an important role in the thought of the Italian Renaissance, particularly within the humanist movement. Interest in Socrates continued unabated, as reflected in the works of Søren Kierkegaard and Friedrich Nietzsche. Depictions of Socrates in art, literature and popular culture have made him one of the most widely known figures in the Western philosophical tradition.", lifespan: "470–399 BC")


Quote.create(passage: "An unexamined life is not worth living.", philosopher: socrates)
Quote.create(passage: "One thing only I know, and that is that I know nothing.", philosopher: socrates)
Quote.create(passage: "To find yourself, think for yourself.", philosopher: socrates)
Quote.create(passage: "When the debate is over, slander becomes the tool of the loser.", philosopher: socrates)

plato = Philosopher.create(name: "Plato", school: socratic, bio: "Plato was an Athenian philosopher during the Classical period in Ancient Greece, founder of the Platonist school of thought and the Academy, the first institution of higher learning in the Western world.

He is widely considered one of the most important and influential individuals in human history, and the pivotal figure in the history of Ancient Greek and Western philosophy, along with his teacher, Socrates, and his most famous student, Aristotle. Plato has also often been cited as one of the founders of Western religion and spirituality. The so-called neoplatonism of philosophers such as Plotinus and Porphyry greatly influenced Christianity through Church Fathers such as Augustine. Alfred North Whitehead once noted: 'the safest general characterization of the European philosophical tradition is that it consists of a series of footnotes to Plato.'

Plato was an innovator of the written dialogue and dialectic forms in philosophy. Plato is also considered the founder of Western political philosophy. His most famous contribution is the theory of Forms known by pure reason, in which Plato presents a solution to the problem of universals known as Platonism (also ambiguously called either Platonic realism or Platonic idealism). He is also the namesake of Platonic love and the Platonic solids.

His own most decisive philosophical influences are usually thought to have been along with Socrates, the pre-Socratics Pythagoras, Heraclitus and Parmenides, although few of his predecessors' works remain extant and much of what we know about these figures today derives from Plato himself.[b] Unlike the work of nearly all of his contemporaries, Plato's entire body of work is believed to have survived intact for over 2,400 years. Although their popularity has fluctuated, Plato's works have consistently been read and studied.", lifespan: " 428/427 or 424/423 – 348/347 BC")

Quote.create(passage: "Thinking: the talking of the soul with itself.", philosopher: plato)
Quote.create(passage: "The greatest wealth is to live content with little.", philosopher: plato)
Quote.create(passage: "Be kind, for everyone you meet is fighting a hard battle.", philosopher: plato)
Quote.create(passage: "Music is a moral law. It gives soul to the universe, wings to the mind, flight to the imagination, and charm and gaiety to life and to everything.", philosopher: plato)
Quote.create(passage: "The first and greatest victory is to conquer yourself; to be conquered by yourself is of all things most shameful and vile.", philosopher: plato)

aristotle = Philosopher.create(name: "Aristotle", school: socratic, bio: "Aristotle was a Greek philosopher and polymath during the Classical period in Ancient Greece. Taught by Plato, he was the founder of the Lyceum, the Peripatetic school of philosophy, and the Aristotelian tradition. His writings cover many subjects including physics, biology, zoology, metaphysics, logic, ethics, aesthetics, poetry, theatre, music, rhetoric, psychology, linguistics, economics, politics, meteorology, geology and government. Aristotle provided a complex synthesis of the various philosophies existing prior to him. It was above all from his teachings that the West inherited its intellectual lexicon, as well as problems and methods of inquiry. As a result, his philosophy has exerted a unique influence on almost every form of knowledge in the West and it continues to be a subject of contemporary philosophical discussion.

Little is known about his life. Aristotle was born in the city of Stagira in Northern Greece. His father, Nicomachus, died when Aristotle was a child, and he was brought up by a guardian. At seventeen or eighteen years of age he joined Plato's Academy in Athens and remained there until the age of thirty-seven (c. 347 BC). Shortly after Plato died, Aristotle left Athens and, at the request of Philip II of Macedon, tutored Alexander the Great beginning in 343 BC. He established a library in the Lyceum which helped him to produce many of his hundreds of books on papyrus scrolls. Though Aristotle wrote many elegant treatises and dialogues for publication, only around a third of his original output has survived, none of it intended for publication.

Aristotle's views profoundly shaped medieval scholarship. The influence of physical science extended from Late Antiquity and the Early Middle Ages into the Renaissance, and were not replaced systematically until the Enlightenment and theories such as classical mechanics were developed. Some of Aristotle's zoological observations found in his biology, such as on the hectocotyl (reproductive) arm of the octopus, were disbelieved until the 19th century. He also influenced Judeo-Islamic philosophies (800–1400) during the Middle Ages, as well as Christian theology, especially the Neoplatonism of the Early Church and the scholastic tradition of the Catholic Church. Aristotle was revered among medieval Muslim scholars as 'The First Teacher', and among medieval Christians like Thomas Aquinas as simply 'The Philosopher', while the poet Dante called him 'the master of those who know'. His works contain the earliest known formal study of logic, and were studied by medieval scholars such as Peter Abelard and John Buridan.

Aristotle's influence on logic continued well into the 19th century. In addition, his ethics, though always influential, gained renewed interest with the modern advent of virtue ethics.

Aristotle has been called 'the father of logic', 'the father of biology', 'the father of political science', 'the father of zoology', 'the father of embryology', 'the father of natural law', 'the father of scientific method', 'the father of rhetoric', 'the father of psychology', 'the father of realism', 'the father of criticism', 'the father of individualism', 'the father of teleology', and 'the father of meteorology'.", lifespan: "384–322 BC")


Quote.create(passage: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", philosopher: aristotle)
Quote.create(passage: "A friend to all is a friend to none.", philosopher: aristotle)
Quote.create(passage: "Pleasure in the job puts perfection in the work.", philosopher: aristotle)
Quote.create(passage: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", philosopher: aristotle)
Quote.create(passage: "The whole is more than the sum of its parts.", philosopher: aristotle)
Quote.create(passage: "The law is reason, free from passion.", philosopher: aristotle)